# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'komentarz',
                'verbose_name_plural': 'komentarze',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Space')),
            ],
            options={
                'verbose_name': 'przestrzeń',
                'verbose_name_plural': 'przestrzenie',
            },
        ),
        migrations.CreateModel(
            name='SpaceUser',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('rights', models.CharField(blank=True, max_length=32, null=True)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Space')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'użytkownik przestrzeni',
                'verbose_name_plural': 'użytkownicy przestrzeni',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Space'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
